### ISSUE TITLE
[Back] 모델 서빙 latency 해결 및 DB 의존성 분리 - fix/model-latency-db-dependency

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI-DDD#10]
### 📌 Description

image retrieval 시 서버에서 latency가 길어지는 문제 확인 및 해결하는 작업을 진행합니다. 또한 dependency injection을 활용하여 DB와 서버 간의 의존성을 분리합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- image retrieval latency 문제 해결
- DB와 서버 간의 의존성 분리

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] image retrieval latency
  - [x] 문제 원인 확인
  - [x] 서버 배포 재작업 tag = 0.0.1
- [ ] dependency injection
  - [ ] account repository
  - [ ] admin repository
  - [ ] user repository
- [ ] 서버 동작 확인
