### ISSUE TITLE
[Back] 추가 기능 연동 feature/additional-function 

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI-DDD#5]
### 📌 Description

image validation을 위한 추가 기능 연동 및 API를 연결합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- image validation 기능을 이미지 입력(insert_image) API에 연동
- 실제 사용할 API 기능 개발

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] PostgreSQL user_content수정
  - [x] status 컬럼 추가
  - [x] image_insert 시 입력
  - [x] generate 에서 기존 함수 제거
- [x] 로그인 기능 연동
  - [x] 로그인 데코레이터
  - [x] user 함수 로그인 추가
- [x] 포커스 포인트 프롬프트 수정
- [x] PostgreSQL 수정
  - [x] user_content -> user_content_review로 수정
  - [x] user_content_review like_status - bool, review - VAR(500) 컬럼 추가, status 컬럼 삭제
  - [x] generated_content 테이블 추가
    - [x] seq, image_name, origin_image(large blob), audio_content(large blob), video_content(large blob)
- [x] MongoDB 수정
  - [x] id -> image_name
- [x] admin domain 분리
  - [x] repository
  - [x] service <- generated content 함수 이전
    - [x] 기존 generated content 함수 삭제
  - [x] application
    - [x] 자동 입력
    - [x] 수동 입력(개별적으로 생성해서 넣는 방식!!)
  - [x] api - admin 
- [x] user api 수정
  - [x] image insert - loading 콘텐츠 삭제
  - [x] content/demo api 에서 DB에 저장된 이미지 전달
  - [x] 콘텐츠 로컬이 아닌 DB에서 가져오도록 코드 수정
    - [x] repository 추가
- [x] API 기능 개발
  - [x] get_text_audio_content application layer
    - [x] resize 이미지 전송 추가(origin_img -> resize_img로 변경)
  - [x] get_coord_content application layer
  - [x] get_video_content application layer
  - [x] get_text_audio_content adapter layer
  - [x] get_coord_content adapter layer
  - [x] get_video_content adapter layer
- [x] 기능 동작 확인
- [x] demo api 수정

**Comment by robert-min** [comment]
# DB 인프라 구축

## 스키마 설정
- db 이름 : art

### user_account
```sql
-- art 데이터베이스 생성
CREATE DATABASE art;

-- art 데이터베이스로 연결
\c art;

-- user_account 테이블 생성
CREATE TABLE user_account (
    seq BIGSERIAL PRIMARY KEY,
    id VARCHAR(500) NOT NULL,
    password BYTEA NOT NULL,
    name VARCHAR(500) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    age VARCHAR(200) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE
);

-- user_account 테이블 삭제
DROP TABLE user_account;

-- user_content 테이블 생성
CREATE TABLE user_content (
    seq BIGSERIAL PRIMARY KEY,
    id VARCHAR(500) NOT NULL,
    generated_id VARCHAR(500) NOT NULL
    status BOOLEAN NOT NULL DEFAULT TRUE
);

-- user_content 테이블 삭제
DROP TABLE user_content ;

```
