### ISSUE TITLE
[Back] 이미지 검증 기능 추가 - feature/resize-retrieval

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/ArtAPI-FastAPI-DDD#6]
### 📌 Description

이미지 크기 고정을 위한 resize, 이미지 화질 개선을 위한 upscale, image-retrieval
 기능을 구현합니다.

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 이미지 resize 기능 추가 (510, 680)
- 이미지 upscale 기능 추가
- 이미지 retrival 기능 추가

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 이미지 검증(image_verification)
  - [x] 이미지 resize 기능 추가(image_resize)
  - [x] 이미지 retrieval기능 추가(image_retrieval)
- [x] 기존 이미지 생성 요청 기능 수정
- [x] 동작 확인
